# This is a basic workflow to help you get started with Actions

name: Reformat

on:
  pull_request:
  schedule:
    - cron: '45 15 * * 3'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Reformatting thing
          chmod +x format.sh
          ./format.sh
          git add .
          git commit -m "Reformat"
          git push https://Itzbenz:${{ secrets.API_TOKEN_GITHUB }}@github.com/o7-Fire/Roblox
